language: python
python:
    - 2.7
install:
    - python setup.py install
    - pip install -r requirements.txt
script:
    - echo "hello world"
    - $TRAVIS_BUILD_DIR/tests/run-test.sh
    - cd $TRAVIS_BUILD_DIR
