sudo: false
dist: trusty
language: python

python:
    - 2.7
install:
    - python setup.py install
    - pip install -r requirements.txt
script:
    - echo "hello world"
    #- sh $TRAVIS_BUILD_DIR/test/run-test.sh
    #- cd $TRAVIS_BUILD_DIR
