---
MXNET_VERSION: "mxnet"
output_path: "./output/cityscape"
symbol: resnet_v1_101_deeplab
gpus: '1'
SCALES:
- 1024
- 2048
default:
  frequent: 100
  kvstore: device
dataset:
  NUM_CLASSES: 19
  dataset: CityScape
  dataset_path: "/data_a/dataset/cityscapes/"
  image_set: leftImg8bit_train
  root_path: "./data/"
  test_image_set: leftImg8bit_val
network:
  FIXED_PARAMS:
  - conv1
  - bn_conv1
  - res2
  - bn2
  - gamma
  - beta
  pretrained: "resnet_v1_101"
  pretrained_epoch: 0
TRAIN:
  warmup: true
  warmup_lr: 0.00005
  # typically we will use 4000 warmup step for single GPU
  warmup_step: 1000
  begin_epoch: 0
  end_epoch: 80
  lr: 0.0005
  lr_step: '40.336'
  model_prefix: "deeplabv2.cs.dcn"
  # size of images for each device
  BATCH_IMAGES: 3
  # scale of cropped image during training
  CROP_HEIGHT: 768
  CROP_WIDTH: 1024
  # whether resume training
  RESUME: false
TEST:
  # size of images for each device
  BATCH_IMAGES: 1
  test_epoch: 80
  tile_height: 768
  tile_width: 1024